### ISSUE TITLE
Docker-compose errors

### ISSUE THREAD

**Issue by artyomLisovskij** [alash3al/httpsify#13]
Hi, i'm trying to connect httpsify via docker-compose like that:
```
version: '3.4'
services: 
  ... some containers ...
  nginx:
    container_name: nginx
    command: wait-for app:8000 -- nginx -g "daemon off;"
    depends_on:
      - app
      - frontend
    image: nginx:alpine
    networks:
      - main
    ports:
      - "80:80"
    restart: on-failure
    volumes:
      - ${PWD}/nginx.conf:/etc/nginx/nginx.conf
      - ${PWD}/wait-for:/bin/wait-for
  httpsify:
    container_name: httpsify
    depends_on:
      - nginx
    image: alash3al/httpsify
    ports:
      - "443:443" 
    volumes:
      - ./httpsify:/.httpsify
    networks:
      - main
networks:
  main:
```

Config is:
```
{
	"a1.somedomain.com": ["http://nginx:81"],
	"a2.somedomain.com": ["http://nginx:82"]
}
```

apps on 80 port(https) are working correctly, but https raise errors:

```
httpsify         | ⇛ Parsing the specified flags ...
httpsify         | ⇛ Loading the provided json hosts file from (/.httpsify/hosts.json) ...
httpsify         | ⇛ Watching the hosts file for any change to hot reload it ...
httpsify         | ⇛ Running the HTTP server on address (:http) ...
httpsify         | ⇛ Running the HTTPS (HTTP/2) server on address (:https) ...
httpsify         | ⇛ Get https://acme-v01.api.letsencrypt.org/directory: x509: certificate signed by unknown authority
httpsify         | 2019/05/01 05:31:00 http: TLS handshake error from 2.95.221.131:56033: acme/autocert: missing certificate
```

How to solve this?

**Comment by artyomLisovskij** [comment]
Solved by such Dockerfile:
```
FROM golang:alpine AS builder

RUN apk add --no-cache git && CGO_ENABLED=0 GOOS=linux go get github.com/alash3al/httpsify
RUN apk add -U --no-cache ca-certificates

FROM scratch
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=builder /go/bin/httpsify /go/bin/httpsify

ENTRYPOINT ["/go/bin/httpsify"]
```

so docker-compose now looks like:
```
version: '3.4'
services: 
  ... some containers ...
  nginx:
    container_name: nginx
    command: wait-for app:8000 -- nginx -g "daemon off;"
    depends_on:
      - app
      - frontend
    image: nginx:alpine
    networks:
      - main
    ports:
      - "80:80"
    restart: on-failure
    volumes:
      - ${PWD}/nginx.conf:/etc/nginx/nginx.conf
      - ${PWD}/wait-for:/bin/wait-for
  httpsify:
    build: './https'
    container_name: httpsify
    command: --redirect
    depends_on:
      - nginx
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./httpsify:/.httpsify
    networks:
      - main
networks:
  main:

```
